language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.2.2"
script:
  - bundle install
  - cd spec/dummy
  - bundle exec rake db:migrate RAILS_ENV=test
  - cd ../..
  - bundle exec rspec spec
addons:
    code_climate:
        repo_token: b7bb30d0d3a9c14f79049c6725fe7c68aaf381bb0c2d52e6327aac91614ec8c9